### ISSUE TITLE
Create your own Stacks community

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#1]
**Bounty:** $300 in STX

**Contribution Points:** 1,000

Building community is not rocket science 🚀 , but that doesn't mean it's easy☝️ . It's all about developing long-lasting relationships with each and every community member while bonding over our shared passion for building a better internet on Bitcoin.

Currently, there are more than 50,000 dedicated community members in the Stacks ecosystem spanning 32 countries. Our goal as a community is to expand this to 100 countries with more than 1,000,000 STX Holders.  

Help grow the Stacks ecosystem by creating an online community through Telegram or any platform you may see fit. Your new community can be built around a particular crypto interest, such as DeFi, DAOs, NFTs, Stacking, STX Mining, Trading, or around a local region. If you're building a local community based on geographic location, please ensure that there isn't an existing community in that region. Check out some of the existing communities here: [https://community.stacks.org/groups](https://community.stacks.org/groups) 

In order to complete this bounty, your community must have more than 150 active members.

**Submission Details**
Please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/6Ekt).

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
