### ISSUE TITLE
Stacking Content Creation

### ISSUE THREAD

**Issue by louiseivan** [stacksgov/stacks-advocates#3]
**Bounty:** 
$50 in STX for Blogs
$100 in STX for Videos

**Bounty Description:** 

Stacking is currently most popular product in the Stacks Ecosystem but it seems like there's a lot of education needed as new Stackers are still asking a lot of basic questions about Stacks, its relation to Bitcoin and how to do Stacking 🤔 

Help accelerate the growth of Stacking by teaching its concept either through a blog post, vlog, TikTok stories, or whatever content medium you’re most comfortable with. Feel free to unlock your creativity as long as the central theme of your content revolves around Stacking and how you can earn Bitcoin thru STX.

**Below are some resources to get you started:**
[Stacking](https://www.stacks.co/stacking) - Learn about the basics
[Stacking.club](https://stacking.club/) - Stacking Explorer
[STX Brand Assets](https://www.stx.design/) - Elevate your content with the Stacks Branding Kit

**Submission Details**
Please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/6Ekt).

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
