### ISSUE TITLE
Create your own Stacks community

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#4]
**Internal Bounty Code: ADV01
Internal Bounty Submission Form:** [https://shrl.ink/6Ekt](https://shrl.ink/6Ekt)
**Bounty: $300 in STX
Bounty Description:** 

Building community is no rocket science, but this doesn't mean it is easy as there's no particular framework for it. It is all about developing long-lasting relationships with every community member while bonding over our passion for building a better internet on Bitcoin.

Currently, there are more than **50,000** dedicated community members in the Stacks ecosystem spanning **32** countries. Our goal as a community is to expand this to **100 countries** while having more than **1,000,000 STX Holders**.  

Help grow the Stacks community by creating your online community thru Telegram or any platform you may see fit. Your new community can be built around a particular field of crypto interest such as DeFi, DAOs, NFTs, Stacking, STX Mining, STX Trading, a local STX community, or whatever crypto interest as long as it relates to STX and BTC. If you're building a local community based on geographic location, please ensure that there isn't a local Stacks community already existing in that area. Check some of the existing communities here: [https://community.stacks.org/groups](https://community.stacks.org/groups) 

This bounty will only be completed if your community has more than 150 active members.

**Submission Details**
Please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/6Ekt).

**Comment by batuhantastekin** [comment]
How can we join this bounty if the community still exist by other members?

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
