### ISSUE TITLE
STX Telegram Moderator

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#5]
- Embody the [Stacks Community Code of Conduct](https://forum.stacks.org/t/request-for-comments-code-of-conduct/11725).
- Being consistently and visibly active in Telegram.
- Run community polls, quizzes or meme competition. Contact @Louise Ivan or @Jenny Mith for possible community prizes.
- Share relevant and trendy information about Stacks and Bitcoin.
- Making the community more fun through creative STX + BTC memes .
- Keeping discussions in the channel focused, spam-free, and non-controversial.
- Redirecting conversations that will benefit other community members.
- Defending the project from FUD (the spreading of Fear, Uncertainty, Doubt)
- Flag inappropriate posts, comments, messages, and files to the admins.
- Refer more Stackers to join the STX Telegram Channel.‍

**Resources:**

[Stacks Official Reddit](https://www.reddit.com/r/stacks) - Here's the official subreddit that you need to manage

[Stacks 101](https://stacks101.com/) -  FAQ managed by the community

[Stacks Telegram Announcement Channel](https://t.me/BlockstackUpdate) - you can find the latest ecosystem announcement here

[Stacks Forum](https://forum.stacks.org/) -  Our technical forum that focuses on technical conversation

**Submission Details**

Only three advocates can participate on this bounty. Eligibility is based on your previous community activity. If you want to participate in this bounty, please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/io2d). 
****

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
