### ISSUE TITLE
STX Master Redditor

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#6]
**Internal Bounty Code: ADV03
Internal Bounty Submission Form: [https://shrl.ink/RwnQ](https://shrl.ink/RwnQ)**
**Bounty: $300 in STX + Reddit Coins
Bounty Description:** 

This bounty awards exclusively for the finest Stacks Reddit Contributors. 

At the Stacks Community, we're always about giving the best community experience. We believe that the first touchpoint is always important especially to new community member that enters our [official Reddit subreddit](https://www.reddit.com/r/stacks). The initial touch base can covert random lurkers into lifetime community members. Trust us, we've seen a lot of great community journeys that started from Reddit as it is one of the most prevalent social media platforms used for sharing links and information. 

Just like Telegram Moderation, we need your help to drive Stacks community growth by moderating our [Stacks Official Reddit](https://www.reddit.com/r/stacks).  Below are some tips and tricks to help you become a master Redditor. 👇🏽

**Reddit Tips and Tricks**

- Embody the [Stacks Community Code of Conduct](https://forum.stacks.org/t/request-for-comments-code-of-conduct/11725) in all interactions that you make since you will get the moderator badge.
- Keep the conversation going on in the [Bi-Weekly Discussion Thread.](https://www.reddit.com/r/stacks/comments/lbdz6a/biweekly_discussion_thread_introduce_yourself_and/)
- Being consistently and visibly active in Reddit.
- Amplify all the latest announcements and ecosystem development.
- Share relevant and trendy information about Stacks and Bitcoin, you can do this by following some of the thought leaders in the space like Muneeb, Jude Nelson, Meltem, Nic Carter, and more.
- Keeping discussions in the channel focused, spam-free, and non-controversial.
- Making the community more fun through creative STX + BTC memes
- Defending the project from FUD (the spreading of Fear, Uncertainty, Doubt)
- Flag inappropriate posts, comments, messages, and files to the admins.

**Resources:**

[Stacks Official Reddit](https://www.reddit.com/r/stacks) - Here's the official subreddit that you need to manage

[Stacks 101](https://stacks101.com/) -  FAQ managed by the community

[Stacks Telegram Announcement Channel](https://t.me/BlockstackUpdate) - you can find the latest ecosystem announcement here

[Stacks Forum](https://forum.stacks.org/) -  Our technical forum that focuses on technical conversation

**Submission Details**

Only three advocates can participate on this bounty. Eligibility is based on your previous community activity. If you want to participate in this bounty, please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/RwnQ).

**Comment by joberding** [comment]
@jennymith I passed this on to my son who is an active Redditor, a current Mod for several subreddits and a Stacker. Wondering if the bounty is a one time thing per person or ongoing. And if so - what's the time period?

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
