### ISSUE TITLE
Stacking Content Creation

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#7]
**Internal Bounty Code: ADV04
Internal Bounty Submission Form:** [https://shrl.ink/PDCj](https://shrl.ink/PDCj)
**Bounty:** 
$50 in STX for Blogs
$100 in STX for Videos

**Bounty Description:** 

Stacking is currently most popular product in the Stacks Ecosystem but it seems like there's a lot of education needed as new Stackers are still asking a lot of basic questions about Stacks, its relation to Bitcoin and how to do Stacking 🤔 Help accelerate the growth of Stacking by teaching its concept either through a blog post, vlog, TikTok stories, or whatever content medium you’re most comfortable with. Feel free to unlock your creativity as long as the central theme of your content revolves around Stacking and how you can earn Bitcoin thru STX.

Remember we're all about amplifying great content, so distribution is key. You need to put as much thought in the distribution of the content as you did in its content.

**Below are some resources to get you started:**
[Stacking](https://www.stacks.co/stacking) - Learn about the basics 
[Stacking.club](https://stacking.club/) - The awesome Stacking explorer
[STX Brand Assets](https://www.stx.design/) - Your design resources tool kit

**Submission Details**

If you want to participate in this bounty, please provide the same information you used to register in the Stacks Advocates Program. Register [here](https://shrl.ink/PDCj).v

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
