### ISSUE TITLE
[EXAMPLE] Jenny Mith: Q2 Contributions

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#8]
**[1. Contribution] [2. Measurable impact] [3. Link(s) proving contribution] [4. Number of points you think you deserve]**

- Went above and beyond to answer support questions on Discord and helped at least 20 new community members: < link > [10]
- Made an intro to Clarity tutorial video that got 1,000 views: < link > [100]
- Hosted a virtual Clarity hackathon that produced 10 unique smart contracts: < link > [1000]

**Total:** 1,110

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
