### ISSUE TITLE
[REFERENCE] How to Assign Points to Contributions

### ISSUE THREAD

**Issue by jennymith** [stacksgov/stacks-advocates#9]
**10 Points =** Low–medium effort contribution that checks at least one of the following boxes:
- [ ] Medium impact (reaches up to 30 people)
- [ ] Reaches new communities
- [ ] Brings on new community members
- [ ] Educates community members about Stacks
- [ ] Empowers community members to build on Stacks

**Examples:** Answering support questions on Discord, Telegram, Reddit, tweeting about Stacks

**100 Points =** Medium–high effort contribution that checks at least two of the following boxes:
- [ ] Medium–high impact (reaches 30+ people)
- [ ] Reaches new communities
- [ ] Brings on new community members
- [ ] Educates community members about Stacks
- [ ] Empowers community members to build on Stacks

**Examples:** Translating documentation, hosting AMAs for local communities

**1000 Points =** High effort (takes a lot of advanced planning) contribution that checks at least three of the following boxes:
- [ ] High impact (reaches 100+ people)
- [ ] Reaches new communities
- [ ] Brings on new community members
- [ ] Educates community members about Stacks
- [ ] Empowers community members to build on Stacks

**Examples:** Successful hackathons, tutorial series, dev tool

**Comment by whoabuddy** [comment]
Closing out before archiving repository as read-only
